### PR TITLE
Update josephus.c

### PR DESCRIPTION
**Pull request by dimoret**
Don't forget to free the memory.

### CODE REVIEW

**Comment by ankitvad** [comment]
It's been quite some time since i've done this, and my C is a bit rusty; but your commit seems wrong.
1)You're introducing a new pointer *tmp for no reason at all. Once introduced, it isn't initialized with a value, that introduces NULL in queue.
2)There is no memory overfllow. A single pointer just keeps referencing a new address location, that is already initialized when the program initiates(the players queue). it's like, 
`a=[1,2,3,4,5,6] #pre-made list)
b=a[0]
b=a[1]
..` and so on, you could delete *p and the queue, i guess, but  introducing *tmp is wasteful, and wrong, AFAIK.
Maybe This will help:
http://stackoverflow.com/questions/16886678/linked-list-issue-loop-iterates-over-wrong-nodes
http://tiryou.com/BX14g8Br/solving-josephus-with-linked-lists.html
https://goo.gl/tPt8lR

What you're doing(if i understand correctly) is introducing tmp, pointing NULL in my queue, removing tmp, Why? The player won't update like this at all..

**Comment by dimoret** [comment]
I am a rookie :p,so,AFAIU:
1)The reason why I introduce the new pointer tmp is to free the useless memory(It do exist).*tmp is not NULL,because it's a local variable(see the link). 
2)           p->next             =             p->next->next            equals to:

```
          1          2          3     
  --->|___|_|--->|___|_|--->|___|_|--->
           |                 ^
           |                 |    
           |_________________| 
```

and,  _2_  is useless now,you should let it 'join' the *tmp(as long as it is not NULL) and free tmp.You can't free that memory directly,so *tmp is necessary,like:

```
          1          2          3     
  --->|___|_|--->|___|_|--->|___|_|--->
           |      ^           ^
           |      |           |    
           |_________________| 
                  |
                  |____(tmp:hello,dude ,now you are part of me,let's die together :P).
```

link:http://stackoverflow.com/questions/1597405/what-happens-to-a-declared-uninitialized-variable-in-c-does-it-have-a-value
and
`<<Data Structure and Algorithm Analysis in C>>`_by Mark Allen Weiss_      (Which i am reading recently and brought me to your github)

(My English sucks,forgive me :P)

**Comment by ankitvad** [comment]
Oh, ok.. You're freeing up memory of the node that i remove from reference in queue, cool.. 

Just to make you understand the problem:
there is a list. [1,2,3,4,5,6,7,8] for example.we have 2 pointers, *p and *q, after initialization, of the LinkedList, *p refers the Last Element in the List(9 Here) and points (->Next) to *q, which refers the first element, so you get a "Circular LL"(I'm confused with your arrows, and multiple next-item pointers in your  diagram, per item-member(1,2,3 in your case).

Your code is wrong, your approach seems correct. That's why initially i said 

> you could delete *p and the queue, i guess, but introducing *tmp is wasteful, and wrong, AFAIK.

```
 +         p = p->next;
 +        struct node *tmp;
 +        p->next = tmp->next;// Remove the eiminated player from the circular linked list.
 +        free(tmp);
```

Here _tmp has no value at all.. It is not pointing to anything. 
Let's see line by line: Assume a List `[1,2,3,4,5]`. `*p` is at `5`, and points ->Next to `*q` which is at `1`.
Your Code:
1)`p=p->next;` Now Your *p is at *q, which is `1`. Cool?
2)`struct node *tmp;` *_You created a New node. here, you haven't assigned any value to _tmp yet._\* So, `tmp->int player_id;` and `struct node *next;` both have no value at all., just a pointer, if you wanna create a new node, which will be done by: `tmp = malloc(sizeof(struct node));`
3)`p->next = tmp->next;` Boom, You broke the LinkedList-Circular Queue. Let's see how ?
`*p` was at `1`, and p->next, would have been 2. You referenced `p->next` to `tmp->next`, and **tmp->next has no value at all, it was never initialised, or assigned a value, so it has some garbage value to it.** and, i'm left with 2 list now:
`[1->GARBAGE_VALUE(tmp)]` and `[2,3,4,5]`, only problem, you deleted all pointer reference to my second list name by destroying `p->next;`. and then,
4)you `free(tmp)` which removes tmp, giving me(i assume) [1] and [2,3,4,5]. Which defeats the whole purpose.

Now, 
1) Your thinking is correct, you want to remove the value i delete from reference, i suggest you should read more thoroughly to accomplish this. I understand what to do now, but since it's your idea, i'd like you to read up on this, and submit a New PR with correct code. :)

**Comment by dimoret** [comment]
Oh god,i made a mistake,I lost :
_tmp = p->next_;
So,actually,I mean:

``` bash
        struct node *tmp;
        tmp = p->next;
        p->next = tmp->next;
        free(tmp);
```

Sorry,it's quite embarrassed.

**Comment by ankitvad** [comment]
You'll need:
`tmp = malloc(sizeof(struct node));`

**Comment by ankitvad** [comment]
Seems Correct. I'm not merging yet, will have to test it once.. Will do in a few hours :)

**Comment by dimoret** [comment]
OK,It's my fault(LOL).

**Comment by ankitvad** [comment]
No man, no fault at all. Thanks for the PR. Seems to be working Correctly:

```
#include <stdio.h>
#include <stdlib.h>



int main()
{
    int N, M;
    struct node { int player_id; struct node *next; };
    struct node *p, *q;
    int i, count;

    //printf("Enter N (number of players): "); scanf("%d", &N);
    //printf("Enter M (every M-th payer gets eliminated): "); scanf("%d", &M);
    N=20;
    M=3;
    // Create circular linked list containing all the players:

    p = q = malloc(sizeof(struct node));

    p->player_id = 1;

    for (i = 2; i <= N; ++i) {
        p->next = malloc(sizeof(struct node));
        p = p->next;
        p->player_id = i;
    }  

    p->next = q;  // Close the circular linked list by having the last node point to the first.

    // Eliminate every M-th player as long as more than one player remains:

    for (count = N; count > 1; --count) {
       for (i = 0; i < M - 1; ++i)
            p = p->next;
        struct node *tmp;
        tmp = p->next;
        printf("Removing: %d\n",tmp->player_id);
        p->next = tmp->next;// Remove the eiminated player from the circular linked list.
        free(tmp);

    }

    printf("Last player left standing is %d\n.", p->player_id);

    return 0;
}

Output:
Removing: 3
Removing: 6
Removing: 9
Removing: 12
Removing: 15
Removing: 18
Removing: 1
Removing: 5
Removing: 10
Removing: 14
Removing: 19
Removing: 4
Removing: 11
Removing: 17
Removing: 7
Removing: 16
Removing: 8
Removing: 2
Removing: 13
Last player left standing is 20
```

**Comment by dimoret** [comment]
**ACHIEVEMENTS UNLOCKED:First PR**
:P 
Your homepage is cool,by the way.

**Pull request merged**
